import React from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, HelpCircle, BookOpen, Cpu, Target, ShieldCheck, Sparkles } from "lucide-react";
import { LuCat } from "react-icons/lu";

function FAQsAndGuides() {
  const navigate = useNavigate();

  return (
    <div
      className="faqs-guides-section"
      style={{
        padding: "32px",
        maxWidth: "850px",
        margin: "0 auto",
        boxSizing: "border-box",
        color: "#FFFFFF",
        fontFamily: "Inter, sans-serif"
      }}
    >
      <button
        type="button"
        onClick={() => navigate("/dashboard")}
        style={{
          backgroundColor: "#7C3AED",
          color: "#FFFFFF",
          border: "none",
          borderRadius: "10px",
          padding: "10px 18px",
          fontWeight: "600",
          fontSize: "14px",
          display: "inline-flex",
          alignItems: "center",
          gap: "8px",
          cursor: "pointer",
          marginBottom: "24px",
          boxShadow: "0px 4px 12px rgba(124, 58, 237, 0.3)",
        }}
      >
        <ArrowLeft size={16} /> Back to Dashboard
      </button>

      <div style={{ backgroundColor: "#161622", border: "1px solid #2E2E42", borderRadius: "16px", padding: "28px", boxShadow: "0px 10px 30px rgba(0,0,0,0.3)" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "12px", marginBottom: "20px" }}>
          <div
            style={{
              padding: "10px",
              backgroundColor: "rgba(124, 58, 237, 0.15)",
              borderRadius: "10px",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            <HelpCircle size={24} color="#A78BFA" />
          </div>
          <div>
            <h2 style={{ fontSize: "22px", fontWeight: "700", margin: "0 0 4px 0" }}>Frequently Asked Questions</h2>
            <p style={{ fontSize: "13px", color: "#9CA3AF", margin: 0 }}>
              Everything you need to know about navigating your AI-powered development tracker.
            </p>
          </div>
        </div>

        <div style={{ display: "flex", flexDirection: "column", gap: "20px" }}>
          
          <div style={{ backgroundColor: "#1F1F2E", border: "1px solid #2E2E42", borderRadius: "12px", padding: "18px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "6px" }}>
              <Target size={16} color="#A78BFA" />
              <strong style={{ color: "#FFFFFF", fontSize: "15px" }}>How is my career readiness score calculated?</strong>
            </div>
            <p style={{ color: "#9CA3AF", fontSize: "13px", margin: 0, lineHeight: "1.6", paddingLeft: "24px" }}>
              Your score dynamically aggregates your full-stack project entries (such as the Wanderlust app), Java DSA practice progress, core technical skills, and resume upload status into a live percentage metric.
            </p>
          </div>

          <div style={{ backgroundColor: "#1F1F2E", border: "1px solid #2E2E42", borderRadius: "12px", padding: "18px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "6px" }}>
              <Sparkles size={16} color="#C084FC" />
              <strong style={{ color: "#FFFFFF", fontSize: "15px" }}>How is my AI Career Roadmap generated?</strong>
            </div>
            <p style={{ color: "#9CA3AF", fontSize: "13px", margin: 0, lineHeight: "1.6", paddingLeft: "24px" }}>
              Your roadmap is generated by comparing the skills, projects, and target role entered in your profile against industry benchmarks. It identifies core skill gaps and organizes a step-by-step milestone plan to help you prepare systematically for your target career path.
            </p>
          </div>

          <div style={{ backgroundColor: "#1F1F2E", border: "1px solid #2E2E42", borderRadius: "12px", padding: "18px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "6px" }}>
              <Cpu size={16} color="#34D399" />
              <strong style={{ color: "#FFFFFF", fontSize: "15px" }}>How do the daily AI study suggestions work?</strong>
            </div>
            <p style={{ color: "#9CA3AF", fontSize: "13px", margin: 0, lineHeight: "1.6", paddingLeft: "24px" }}>
              The system generates a personalized, daily-rolling study plan tailored to your MERN stack background and AI engineering focus. Tasks rotate automatically every single day to keep your learning consistent.
            </p>
          </div>

          <div style={{ backgroundColor: "#1F1F2E", border: "1px solid #2E2E42", borderRadius: "12px", padding: "18px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "6px" }}>
              <BookOpen size={16} color="#F59E0B" />
              <strong style={{ color: "#FFFFFF", fontSize: "15px" }}>How can I track my Data Structures & Algorithms (DSA) progress?</strong>
            </div>
            <p style={{ color: "#9CA3AF", fontSize: "13px", margin: 0, lineHeight: "1.6", paddingLeft: "24px" }}>
              Navigate to the dedicated <code style={{ color: "#A78BFA", background: "#2E2E42", padding: "2px 6px", borderRadius: "4px" }}>/dsa-tracker</code> route to log problem-solving milestones in Java, practice array patterns, and monitor your consistency.
            </p>
          </div>

          <div style={{ backgroundColor: "#1F1F2E", border: "1px solid #2E2E42", borderRadius: "12px", padding: "18px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "6px" }}>
              <Target size={16} color="#3B82F6" />
              <strong style={{ color: "#FFFFFF", fontSize: "15px" }}>Can I add custom metrics and projects?</strong>
            </div>
            <p style={{ color: "#9CA3AF", fontSize: "13px", margin: 0, lineHeight: "1.6", paddingLeft: "24px" }}>
              Yes! Use the &quot;+ Add New&quot; button on your dashboard header to create custom tracker cards for your portfolio projects, ML internships, or certificates.
            </p>
          </div>

          <div style={{ backgroundColor: "#1F1F2E", border: "1px solid #2E2E42", borderRadius: "12px", padding: "18px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "6px" }}>
              <ShieldCheck size={16} color="#EC4899" />
              <strong style={{ color: "#FFFFFF", fontSize: "15px" }}>Where can I update my profile handles and resume?</strong>
            </div>
            <p style={{ color: "#9CA3AF", fontSize: "13px", margin: 0, lineHeight: "1.6", paddingLeft: "24px" }}>
              Go to the <b>Settings</b> page to update your GitHub, LinkedIn, LeetCode handles, bio, target role, or upload a new PDF resume file securely.
            </p>
          </div>
          
          <div style={{ backgroundColor: "#1F1F2E", border: "1px solid #2E2E42", borderRadius: "12px", padding: "18px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "6px" }}>
              <LuCat size={16} color="#C084FC" />
              <strong style={{ color: "#FFFFFF", fontSize: "15px" }}>What's the story behind the cat logo?</strong>
            </div>
            <p style={{ color: "#9CA3AF", fontSize: "13px", margin: 0, lineHeight: "1.6", paddingLeft: "24px" }}>
              I absolutely adore cats and their calm energy. Job hunting and upskilling can get stressful, so I wanted to bring a little bit of that feline cuteness into CareerTrack AI to make working on your goals feel lighter and more encouraging.
            </p>
          </div>

        </div>
      </div>
    </div>
  );
}

export default FAQsAndGuides;