const dsaQuestions = [
  // --- 1. Array & Hashing ---
  { title: "Two Sum", category: "Array", difficulty: "Easy", link: "https://leetcode.com/problems/two-sum/" },
  { title: "Best Time to Buy and Sell Stock", category: "Array", difficulty: "Easy", link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/" },
  { title: "Contains Duplicate", category: "Array", difficulty: "Easy", link: "https://leetcode.com/problems/contains-duplicate/" },
  { title: "Valid Anagram", category: "Array", difficulty: "Easy", link: "https://leetcode.com/problems/valid-anagram/" },
  { title: "Missing Number", category: "Array", difficulty: "Easy", link: "https://leetcode.com/problems/missing-number/" },
  { title: "Plus One", category: "Array", difficulty: "Easy", link: "https://leetcode.com/problems/plus-one/" },
  { title: "Majority Element", category: "Array", difficulty: "Easy", link: "https://leetcode.com/problems/majority-element/" },
  { title: "Single Number", category: "Array", difficulty: "Easy", link: "https://leetcode.com/problems/single-number/" },
  { title: "Product of Array Except Self", category: "Array", difficulty: "Medium", link: "https://leetcode.com/problems/product-of-array-except-self/" },
  { title: "Maximum Subarray", category: "Array", difficulty: "Medium", link: "https://leetcode.com/problems/maximum-subarray/" },
  { title: "Find Minimum in Rotated Sorted Array", category: "Array", difficulty: "Medium", link: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/" },
  { title: "Search in Rotated Sorted Array", category: "Array", difficulty: "Medium", link: "https://leetcode.com/problems/search-in-rotated-sorted-array/" },
  { title: "3Sum", category: "Array", difficulty: "Medium", link: "https://leetcode.com/problems/3sum/" },
  { title: "Container With Most Water", category: "Array", difficulty: "Medium", link: "https://leetcode.com/problems/container-with-most-water/" },
  { title: "Group Anagrams", category: "Array", difficulty: "Medium", link: "https://leetcode.com/problems/group-anagrams/" },
  { title: "Top K Frequent Elements", category: "Array", difficulty: "Medium", link: "https://leetcode.com/problems/top-k-frequent-elements/" },
  { title: "Longest Consecutive Sequence", category: "Array", difficulty: "Medium", link: "https://leetcode.com/problems/longest-consecutive-sequence/" },
  { title: "Subarray Sum Equals K", category: "Array", difficulty: "Medium", link: "https://leetcode.com/problems/subarray-sum-equals-k/" },
  { title: "Spiral Matrix", category: "Array", difficulty: "Medium", link: "https://leetcode.com/problems/spiral-matrix/" },
  { title: "Set Matrix Zeroes", category: "Array", difficulty: "Medium", link: "https://leetcode.com/problems/set-matrix-zeroes/" },
  { title: "First Missing Positive", category: "Array", difficulty: "Hard", link: "https://leetcode.com/problems/first-missing-positive/" },
  { title: "Trapping Rain Water", category: "Array", difficulty: "Hard", link: "https://leetcode.com/problems/trapping-rain-water/" },
  { title: "Median of Two Sorted Arrays", category: "Array", difficulty: "Hard", link: "https://leetcode.com/problems/median-of-two-sorted-arrays/" },
  { title: "Largest Rectangle in Histogram", category: "Array", difficulty: "Hard", link: "https://leetcode.com/problems/largest-rectangle-in-histogram/" },
  { title: "Minimum Window Substring", category: "Array", difficulty: "Hard", link: "https://leetcode.com/problems/minimum-window-substring/" },

  // --- 2. Two Pointers ---
  { title: "Valid Palindrome", category: "Two Pointers", difficulty: "Easy", link: "https://leetcode.com/problems/valid-palindrome/" },
  { title: "Move Zeroes", category: "Two Pointers", difficulty: "Easy", link: "https://leetcode.com/problems/move-zeroes/" },
  { title: "Remove Element", category: "Two Pointers", difficulty: "Easy", link: "https://leetcode.com/problems/remove-element/" },
  { title: "Reverse String", category: "Two Pointers", difficulty: "Easy", link: "https://leetcode.com/problems/reverse-string/" },
  { title: "Valid Anagram", category: "Two Pointers", difficulty: "Easy", link: "https://leetcode.com/problems/valid-anagram/" },
  { title: "Merge Sorted Array", category: "Two Pointers", difficulty: "Easy", link: "https://leetcode.com/problems/merge-sorted-array/" },
  { title: "Remove Duplicates from Sorted Array", category: "Two Pointers", difficulty: "Easy", link: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/" },
  { title: "Two Sum II - Input Array Is Sorted", category: "Two Pointers", difficulty: "Medium", link: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/" },
  { title: "3Sum", category: "Two Pointers", difficulty: "Medium", link: "https://leetcode.com/problems/3sum/" },
  { title: "3Sum Closest", category: "Two Pointers", difficulty: "Medium", link: "https://leetcode.com/problems/3sum-closest/" },
  { title: "Container With Most Water", category: "Two Pointers", difficulty: "Medium", link: "https://leetcode.com/problems/container-with-most-water/" },
  { title: "Sort Colors", category: "Two Pointers", difficulty: "Medium", link: "https://leetcode.com/problems/sort-colors/" },
  { title: "Partition Labels", category: "Two Pointers", difficulty: "Medium", link: "https://leetcode.com/problems/partition-labels/" },
  { title: "Reverse Words in a String", category: "Two Pointers", difficulty: "Medium", link: "https://leetcode.com/problems/reverse-words-in-a-string/" },
  { title: "4Sum", category: "Two Pointers", difficulty: "Medium", link: "https://leetcode.com/problems/4sum/" },
  { title: "Interval List Intersections", category: "Two Pointers", difficulty: "Medium", link: "https://leetcode.com/problems/interval-list-intersections/" },
  { title: "Trapping Rain Water", category: "Two Pointers", difficulty: "Hard", link: "https://leetcode.com/problems/trapping-rain-water/" },
  { title: "Minimum Window Substring", category: "Two Pointers", difficulty: "Hard", link: "https://leetcode.com/problems/minimum-window-substring/" },
  { title: "Substring with Concatenation of All Words", category: "Two Pointers", difficulty: "Hard", link: "https://leetcode.com/problems/substring-with-concatenation-of-all-words/" },

  // --- 3. Sliding Window ---
  { title: "Maximum Average Subarray I", category: "Sliding Window", difficulty: "Easy", link: "https://leetcode.com/problems/maximum-average-subarray-i/" },
  { title: "Contains Duplicate II", category: "Sliding Window", difficulty: "Easy", link: "https://leetcode.com/problems/contains-duplicate-ii/" },
  { title: "Longest Substring Without Repeating Characters", category: "Sliding Window", difficulty: "Medium", link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
  { title: "Longest Repeating Character Replacement", category: "Sliding Window", difficulty: "Medium", link: "https://leetcode.com/problems/longest-repeating-character-replacement/" },
  { title: "Permutation in String", category: "Sliding Window", difficulty: "Medium", link: "https://leetcode.com/problems/permutation-in-string/" },
  { title: "Minimum Size Subarray Sum", category: "Sliding Window", difficulty: "Medium", link: "https://leetcode.com/problems/minimum-size-subarray-sum/" },
  { title: "Find All Anagrams in a String", category: "Sliding Window", difficulty: "Medium", link: "https://leetcode.com/problems/find-all-anagrams-in-a-string/" },
  { title: "Max Consecutive Ones III", category: "Sliding Window", difficulty: "Medium", link: "https://leetcode.com/problems/max-consecutive-ones-iii/" },
  { title: "Fruit Into Baskets", category: "Sliding Window", difficulty: "Medium", link: "https://leetcode.com/problems/fruit-into-baskets/" },
  { title: "Longest Substring with At Most K Distinct Characters", category: "Sliding Window", difficulty: "Medium", link: "https://leetcode.com/problems/longest-substring-with-at-most-k-distinct-characters/" },
  { title: "Subarray Product Less Than K", category: "Sliding Window", difficulty: "Medium", link: "https://leetcode.com/problems/subarray-product-less-than-k/" },
  { title: "Maximum Number of Vowels in a Substring of Given Length", category: "Sliding Window", difficulty: "Medium", link: "https://leetcode.com/problems/maximum-number-of-vowels-in-a-substring-of-given-length/" },
  { title: "Grumpy Bookstore Owner", category: "Sliding Window", difficulty: "Medium", link: "https://leetcode.com/problems/grumpy-bookstore-owner/" },
  { title: "Minimum Window Substring", category: "Sliding Window", difficulty: "Hard", link: "https://leetcode.com/problems/minimum-window-substring/" },
  { title: "Sliding Window Maximum", category: "Sliding Window", difficulty: "Hard", link: "https://leetcode.com/problems/sliding-window-maximum/" },
  { title: "Subarrays with K Different Integers", category: "Sliding Window", difficulty: "Hard", link: "https://leetcode.com/problems/subarrays-with-k-different-integers/" },
  { title: "Substring with Concatenation of All Words", category: "Sliding Window", difficulty: "Hard", link: "https://leetcode.com/problems/substring-with-concatenation-of-all-words/" },

  // --- 4. Stack ---
  { title: "Valid Parentheses", category: "Stack", difficulty: "Easy", link: "https://leetcode.com/problems/valid-parentheses/" },
  { title: "Next Greater Element I", category: "Stack", difficulty: "Easy", link: "https://leetcode.com/problems/next-greater-element-i/" },
  { title: "Implement Queue using Stacks", category: "Stack", difficulty: "Easy", link: "https://leetcode.com/problems/implement-queue-using-stacks/" },
  { title: "Backspace String Compare", category: "Stack", difficulty: "Easy", link: "https://leetcode.com/problems/backspace-string-compare/" },
  { title: "Make The String Great", category: "Stack", difficulty: "Easy", link: "https://leetcode.com/problems/make-the-string-great/" },
  { title: "Min Stack", category: "Stack", difficulty: "Medium", link: "https://leetcode.com/problems/min-stack/" },
  { title: "Evaluate Reverse Polish Notation", category: "Stack", difficulty: "Medium", link: "https://leetcode.com/problems/evaluate-reverse-polish-notation/" },
  { title: "Generate Parentheses", category: "Stack", difficulty: "Medium", link: "https://leetcode.com/problems/generate-parentheses/" },
  { title: "Daily Temperatures", category: "Stack", difficulty: "Medium", link: "https://leetcode.com/problems/daily-temperatures/" },
  { title: "Car Fleet", category: "Stack", difficulty: "Medium", link: "https://leetcode.com/problems/car-fleet/" },
  { title: "Online Stock Span", category: "Stack", difficulty: "Medium", link: "https://leetcode.com/problems/online-stock-span/" },
  { title: "Asteroid Collision", category: "Stack", difficulty: "Medium", link: "https://leetcode.com/problems/asteroid-collision/" },
  { title: "Simplify Path", category: "Stack", difficulty: "Medium", link: "https://leetcode.com/problems/simplify-path/" },
  { title: "Decode String", category: "Stack", difficulty: "Medium", link: "https://leetcode.com/problems/decode-string/" },
  { title: "Remove K Digits", category: "Stack", difficulty: "Medium", link: "https://leetcode.com/problems/remove-k-digits/" },
  { title: "Largest Rectangle in Histogram", category: "Stack", difficulty: "Hard", link: "https://leetcode.com/problems/largest-rectangle-in-histogram/" },
  { title: "Basic Calculator", category: "Stack", difficulty: "Hard", link: "https://leetcode.com/problems/basic-calculator/" },
  { title: "Maximal Rectangle", category: "Stack", difficulty: "Hard", link: "https://leetcode.com/problems/maximal-rectangle/" },

  // --- 5. Binary Search ---
  { title: "Binary Search", category: "Binary Search", difficulty: "Easy", link: "https://leetcode.com/problems/binary-search/" },
  { title: "Sqrt(x)", category: "Binary Search", difficulty: "Easy", link: "https://leetcode.com/problems/sqrtx/" },
  { title: "Guess Number Higher or Lower", category: "Binary Search", difficulty: "Easy", link: "https://leetcode.com/problems/guess-number-higher-or-lower/" },
  { title: "First Bad Version", category: "Binary Search", difficulty: "Easy", link: "https://leetcode.com/problems/first-bad-version/" },
  { title: "Valid Perfect Square", category: "Binary Search", difficulty: "Easy", link: "https://leetcode.com/problems/valid-perfect-square/" },
  { title: "Search a 2D Matrix", category: "Binary Search", difficulty: "Medium", link: "https://leetcode.com/problems/search-a-2d-matrix/" },
  { title: "Koko Eating Bananas", category: "Binary Search", difficulty: "Medium", link: "https://leetcode.com/problems/koko-eating-bananas/" },
  { title: "Time Based Key-Value Store", category: "Binary Search", difficulty: "Medium", link: "https://leetcode.com/problems/time-based-key-value-store/" },
  { title: "Find First and Last Position of Element in Sorted Array", category: "Binary Search", difficulty: "Medium", link: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/" },
  { title: "Find Peak Element", category: "Binary Search", difficulty: "Medium", link: "https://leetcode.com/problems/find-peak-element/" },
  { title: "Capacity To Ship Packages Within D Days", category: "Binary Search", difficulty: "Medium", link: "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/" },
  { title: "Single Element in a Sorted Array", category: "Binary Search", difficulty: "Medium", link: "https://leetcode.com/problems/single-element-in-a-sorted-array/" },
  { title: "Search in Rotated Sorted Array", category: "Binary Search", difficulty: "Medium", link: "https://leetcode.com/problems/search-in-rotated-sorted-array/" },
  { title: "Search in Rotated Sorted Array II", category: "Binary Search", difficulty: "Medium", link: "https://leetcode.com/problems/search-in-rotated-sorted-array-ii/" },
  { title: "Median of Two Sorted Arrays", category: "Binary Search", difficulty: "Hard", link: "https://leetcode.com/problems/median-of-two-sorted-arrays/" },
  { title: "Split Array Largest Sum", category: "Binary Search", difficulty: "Hard", link: "https://leetcode.com/problems/split-array-largest-sum/" },
  { title: "Find Minimum in Rotated Sorted Array II", category: "Binary Search", difficulty: "Hard", link: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array-ii/" },
  
  // --- 6. Linked List ---
  { title: "Reverse Linked List", category: "Linked List", difficulty: "Easy", link: "https://leetcode.com/problems/reverse-linked-list/" },
  { title: "Linked List Cycle", category: "Linked List", difficulty: "Easy", link: "https://leetcode.com/problems/linked-list-cycle/" },
  { title: "Merge Two Sorted Lists", category: "Linked List", difficulty: "Easy", link: "https://leetcode.com/problems/merge-two-sorted-lists/" },
  { title: "Palindrome Linked List", category: "Linked List", difficulty: "Easy", link: "https://leetcode.com/problems/palindrome-linked-list/" },
  { title: "Intersection of Two Linked Lists", category: "Linked List", difficulty: "Easy", link: "https://leetcode.com/problems/intersection-of-two-linked-lists/" },
  { title: "Middle of the Linked List", category: "Linked List", difficulty: "Easy", link: "https://leetcode.com/problems/middle-of-the-linked-list/" },
  { title: "Remove Linked List Elements", category: "Linked List", difficulty: "Easy", link: "https://leetcode.com/problems/remove-linked-list-elements/" },
  { title: "Remove Nth Node From End of List", category: "Linked List", difficulty: "Medium", link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/" },
  { title: "Reorder List", category: "Linked List", difficulty: "Medium", link: "https://leetcode.com/problems/reorder-list/" },
  { title: "Copy List with Random Pointer", category: "Linked List", difficulty: "Medium", link: "https://leetcode.com/problems/copy-list-with-random-pointer/" },
  { title: "Add Two Numbers", category: "Linked List", difficulty: "Medium", link: "https://leetcode.com/problems/add-two-numbers/" },
  { title: "Find the Duplicate Number", category: "Linked List", difficulty: "Medium", link: "https://leetcode.com/problems/find-the-duplicate-number/" },
  { title: "LRU Cache", category: "Linked List", difficulty: "Medium", link: "https://leetcode.com/problems/lru-cache/" },
  { title: "Odd Even Linked List", category: "Linked List", difficulty: "Medium", link: "https://leetcode.com/problems/odd-even-linked-list/" },
  { title: "Swap Nodes in Pairs", category: "Linked List", difficulty: "Medium", link: "https://leetcode.com/problems/swap-nodes-in-pairs/" },
  { title: "Rotate List", category: "Linked List", difficulty: "Medium", link: "https://leetcode.com/problems/rotate-list/" },
  { title: "Merge k Sorted Lists", category: "Linked List", difficulty: "Hard", link: "https://leetcode.com/problems/merge-k-sorted-lists/" },
  { title: "Reverse Nodes in k-Group", category: "Linked List", difficulty: "Hard", link: "https://leetcode.com/problems/reverse-nodes-in-k-group/" },
  { title: "LFU Cache", category: "Linked List", difficulty: "Hard", link: "https://leetcode.com/problems/lfu-cache/" },

  // --- 7. Trees ---
  { title: "Invert Binary Tree", category: "Tree", difficulty: "Easy", link: "https://leetcode.com/problems/invert-binary-tree/" },
  { title: "Maximum Depth of Binary Tree", category: "Tree", difficulty: "Easy", link: "https://leetcode.com/problems/maximum-depth-of-binary-tree/" },
  { title: "Diameter of Binary Tree", category: "Tree", difficulty: "Easy", link: "https://leetcode.com/problems/diameter-of-binary-tree/" },
  { title: "Balanced Binary Tree", category: "Tree", difficulty: "Easy", link: "https://leetcode.com/problems/balanced-binary-tree/" },
  { title: "Same Tree", category: "Tree", difficulty: "Easy", link: "https://leetcode.com/problems/same-tree/" },
  { title: "Subtree of Another Tree", category: "Tree", difficulty: "Easy", link: "https://leetcode.com/problems/subtree-of-another-tree/" },
  { title: "Symmetric Tree", category: "Tree", difficulty: "Easy", link: "https://leetcode.com/problems/symmetric-tree/" },
  { title: "Lowest Common Ancestor of a Binary Search Tree", category: "Tree", difficulty: "Medium", link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/" },
  { title: "Binary Tree Level Order Traversal", category: "Tree", difficulty: "Medium", link: "https://leetcode.com/problems/binary-tree-level-order-traversal/" },
  { title: "Binary Tree Right Side View", category: "Tree", difficulty: "Medium", link: "https://leetcode.com/problems/binary-tree-right-side-view/" },
  { title: "Count Good Nodes in Binary Tree", category: "Tree", difficulty: "Medium", link: "https://leetcode.com/problems/count-good-nodes-in-binary-tree/" },
  { title: "Validate Binary Search Tree", category: "Tree", difficulty: "Medium", link: "https://leetcode.com/problems/validate-binary-search-tree/" },
  { title: "Kth Smallest Element in a BST", category: "Tree", difficulty: "Medium", link: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/" },
  { title: "Construct Binary Tree from Preorder and Inorder Traversal", category: "Tree", difficulty: "Medium", link: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/" },
  { title: "Lowest Common Ancestor of a Binary Tree", category: "Tree", difficulty: "Medium", link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/" },
  { title: "Flatten Binary Tree to Linked List", category: "Tree", difficulty: "Medium", link: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/" },
  { title: "Binary Tree Maximum Path Sum", category: "Tree", difficulty: "Hard", link: "https://leetcode.com/problems/binary-tree-maximum-path-sum/" },
  { title: "Serialize and Deserialize Binary Tree", category: "Tree", difficulty: "Hard", link: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/" },
  { title: "Recover Binary Search Tree", category: "Tree", difficulty: "Hard", link: "https://leetcode.com/problems/recover-binary-search-tree/" },

  // --- 8. Tries ---
  { title: "Longest Common Prefix", category: "Trie", difficulty: "Easy", link: "https://leetcode.com/problems/longest-common-prefix/" },
  { title: "Index Pairs of a String", category: "Trie", difficulty: "Easy", link: "https://leetcode.com/problems/index-pairs-of-a-string/" },
  { title: "Implement Trie (Prefix Tree)", category: "Trie", difficulty: "Medium", link: "https://leetcode.com/problems/implement-trie-prefix-tree/" },
  { title: "Design Add and Search Words Data Structure", category: "Trie", difficulty: "Medium", link: "https://leetcode.com/problems/design-add-and-search-words-data-structure/" },
  { title: "Replace Words", category: "Trie", difficulty: "Medium", link: "https://leetcode.com/problems/replace-words/" },
  { title: "Longest Word in Dictionary", category: "Trie", difficulty: "Medium", link: "https://leetcode.com/problems/longest-word-in-dictionary/" },
  { title: "Implement Magic Dictionary", category: "Trie", difficulty: "Medium", link: "https://leetcode.com/problems/implement-magic-dictionary/" },
  { title: "Map Sum Pairs", category: "Trie", difficulty: "Medium", link: "https://leetcode.com/problems/map-sum-pairs/" },
  { title: "Search Suggestions System", category: "Trie", difficulty: "Medium", link: "https://leetcode.com/problems/search-suggestions-system/" },
  { title: "Camelcase Matching", category: "Trie", difficulty: "Medium", link: "https://leetcode.com/problems/camelcase-matching/" },
  { title: "Maximum XOR of Two Numbers in an Array", category: "Trie", difficulty: "Medium", link: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/" },
  { title: "Short Encoding of Words", category: "Trie", difficulty: "Medium", link: "https://leetcode.com/problems/short-encoding-of-words/" },
  { title: "Word Search II", category: "Trie", difficulty: "Hard", link: "https://leetcode.com/problems/word-search-ii/" },
  { title: "Stream of Characters", category: "Trie", difficulty: "Hard", link: "https://leetcode.com/problems/stream-of-characters/" },
  { title: "Concatenated Words", category: "Trie", difficulty: "Hard", link: "https://leetcode.com/problems/concatenated-words/" },
  { title: "Palindrome Pairs", category: "Trie", difficulty: "Hard", link: "https://leetcode.com/problems/palindrome-pairs/" },
  { title: "Word Break II", category: "Trie", difficulty: "Hard", link: "https://leetcode.com/problems/word-break-ii/" },
  { title: "Prefix and Suffix Search", category: "Trie", difficulty: "Hard", link: "https://leetcode.com/problems/prefix-and-suffix-search/" },

  // --- 9. Heap / Priority Queue ---
  { title: "Kth Largest Element in a Stream", category: "Heap", difficulty: "Easy", link: "https://leetcode.com/problems/kth-largest-element-in-a-stream/" },
  { title: "Last Stone Weight", category: "Heap", difficulty: "Easy", link: "https://leetcode.com/problems/last-stone-weight/" },
  { title: "The K Weakest Rows in a Matrix", category: "Heap", difficulty: "Easy", link: "https://leetcode.com/problems/the-k-weakest-rows-in-a-matrix/" },
  { title: "Relative Ranks", category: "Heap", difficulty: "Easy", link: "https://leetcode.com/problems/relative-ranks/" },
  { title: "Maximum Product of Two Elements in an Array", category: "Heap", difficulty: "Easy", link: "https://leetcode.com/problems/maximum-product-of-two-elements-in-an-array/" },
  { title: "K Closest Points to Origin", category: "Heap", difficulty: "Medium", link: "https://leetcode.com/problems/k-closest-points-to-origin/" },
  { title: "Kth Largest Element in an Array", category: "Heap", difficulty: "Medium", link: "https://leetcode.com/problems/kth-largest-element-in-an-array/" },
  { title: "Task Scheduler", category: "Heap", difficulty: "Medium", link: "https://leetcode.com/problems/task-scheduler/" },
  { title: "Design Twitter", category: "Heap", difficulty: "Medium", link: "https://leetcode.com/problems/design-twitter/" },
  { title: "Reorganize String", category: "Heap", difficulty: "Medium", link: "https://leetcode.com/problems/reorganize-string/" },
  { title: "Top K Frequent Words", category: "Heap", difficulty: "Medium", link: "https://leetcode.com/problems/top-k-frequent-words/" },
  { title: "Sort Characters By Frequency", category: "Heap", difficulty: "Medium", link: "https://leetcode.com/problems/sort-characters-by-frequency/" },
  { title: "Ugly Number II", category: "Heap", difficulty: "Medium", link: "https://leetcode.com/problems/ugly-number-ii/" },
  { title: "Find K Pairs with Smallest Sums", category: "Heap", difficulty: "Medium", link: "https://leetcode.com/problems/find-k-pairs-with-smallest-sums/" },
  { title: "Find Median from Data Stream", category: "Heap", difficulty: "Hard", link: "https://leetcode.com/problems/find-median-from-data-stream/" },
  { title: "Maximum Performance of a Team", category: "Heap", difficulty: "Hard", link: "https://leetcode.com/problems/maximum-performance-of-a-team/" },
  { title: "Meeting Rooms III", category: "Heap", difficulty: "Hard", link: "https://leetcode.com/problems/meeting-rooms-iii/" },
  { title: "IPO", category: "Heap", difficulty: "Hard", link: "https://leetcode.com/problems/ipo/" },
  { title: "Sliding Window Median", category: "Heap", difficulty: "Hard", link: "https://leetcode.com/problems/sliding-window-median/" },
  { title: "Smallest Range Covering Elements from K Lists", category: "Heap", difficulty: "Hard", link: "https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists/" },
  { title: "Minimum Cost to Hire K Workers", category: "Heap", difficulty: "Hard", link: "https://leetcode.com/problems/minimum-cost-to-hire-k-workers/" },
  { title: "Trapping Rain Water II", category: "Heap", difficulty: "Hard", link: "https://leetcode.com/problems/trapping-rain-water-ii/" },

  // --- 10. Backtracking ---
  { title: "Binary Watch", category: "Backtracking", difficulty: "Easy", link: "https://leetcode.com/problems/binary-watch/" },
  { title: "Sum of All Subset XOR Totals", category: "Backtracking", difficulty: "Easy", link: "https://leetcode.com/problems/sum-of-all-subset-xor-totals/" },
  { title: "Subsets", category: "Backtracking", difficulty: "Medium", link: "https://leetcode.com/problems/subsets/" },
  { title: "Subsets II", category: "Backtracking", difficulty: "Medium", link: "https://leetcode.com/problems/subsets-ii/" },
  { title: "Combinations", category: "Backtracking", difficulty: "Medium", link: "https://leetcode.com/problems/combinations/" },
  { title: "Combination Sum", category: "Backtracking", difficulty: "Medium", link: "https://leetcode.com/problems/combination-sum/" },
  { title: "Combination Sum II", category: "Backtracking", difficulty: "Medium", link: "https://leetcode.com/problems/combination-sum-ii/" },
  { title: "Combination Sum III", category: "Backtracking", difficulty: "Medium", link: "https://leetcode.com/problems/combination-sum-iii/" },
  { title: "Permutations", category: "Backtracking", difficulty: "Medium", link: "https://leetcode.com/problems/permutations/" },
  { title: "Permutations II", category: "Backtracking", difficulty: "Medium", link: "https://leetcode.com/problems/permutations-ii/" },
  { title: "Word Search", category: "Backtracking", difficulty: "Medium", link: "https://leetcode.com/problems/word-search/" },
  { title: "Palindrome Partitioning", category: "Backtracking", difficulty: "Medium", link: "https://leetcode.com/problems/palindrome-partitioning/" },
  { title: "Letter Combinations of a Phone Number", category: "Backtracking", difficulty: "Medium", link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/" },
  { title: "Restore IP Addresses", category: "Backtracking", difficulty: "Medium", link: "https://leetcode.com/problems/restore-ip-addresses/" },
  { title: "Matchsticks to Square", category: "Backtracking", difficulty: "Medium", link: "https://leetcode.com/problems/matchsticks-to-square/" },
  { title: "Partition to K Equal Sum Subsets", category: "Backtracking", difficulty: "Medium", link: "https://leetcode.com/problems/partition-to-k-equal-sum-subsets/" },
  { title: "Beautiful Arrangement", category: "Backtracking", difficulty: "Medium", link: "https://leetcode.com/problems/beautiful-arrangement/" },
  { title: "N-Queens", category: "Backtracking", difficulty: "Hard", link: "https://leetcode.com/problems/n-queens/" },
  { title: "N-Queens II", category: "Backtracking", difficulty: "Hard", link: "https://leetcode.com/problems/n-queens-ii/" },
  { title: "Sudoku Solver", category: "Backtracking", difficulty: "Hard", link: "https://leetcode.com/problems/sudoku-solver/" },
  { title: "Unique Paths III", category: "Backtracking", difficulty: "Hard", link: "https://leetcode.com/problems/unique-paths-iii/" },

  // --- 11. Graphs ---
  { title: "Find if Path Exists in Graph", category: "Graph", difficulty: "Easy", link: "https://leetcode.com/problems/find-if-path-exists-in-graph/" },
  { title: "Find the Town Judge", category: "Graph", difficulty: "Easy", link: "https://leetcode.com/problems/find-the-town-judge/" },
  { title: "Flood Fill", category: "Graph", difficulty: "Easy", link: "https://leetcode.com/problems/flood-fill/" },
  { title: "Island Perimeter", category: "Graph", difficulty: "Easy", link: "https://leetcode.com/problems/island-perimeter/" },
  { title: "Number of Islands", category: "Graph", difficulty: "Medium", link: "https://leetcode.com/problems/number-of-islands/" },
  { title: "Max Area of Island", category: "Graph", difficulty: "Medium", link: "https://leetcode.com/problems/max-area-of-island/" },
  { title: "Clone Graph", category: "Graph", difficulty: "Medium", link: "https://leetcode.com/problems/clone-graph/" },
  { title: "Pacific Atlantic Water Flow", category: "Graph", difficulty: "Medium", link: "https://leetcode.com/problems/pacific-atlantic-water-flow/" },
  { title: "Surrounded Regions", category: "Graph", difficulty: "Medium", link: "https://leetcode.com/problems/surrounded-regions/" },
  { title: "Rotting Oranges", category: "Graph", difficulty: "Medium", link: "https://leetcode.com/problems/rotting-oranges/" },
  { title: "Course Schedule", category: "Graph", difficulty: "Medium", link: "https://leetcode.com/problems/course-schedule/" },
  { title: "Course Schedule II", category: "Graph", difficulty: "Medium", link: "https://leetcode.com/problems/course-schedule-ii/" },
  { title: "Is Graph Bipartite?", category: "Graph", difficulty: "Medium", link: "https://leetcode.com/problems/is-graph-bipartite/" },
  { title: "Redundant Connection", category: "Graph", difficulty: "Medium", link: "https://leetcode.com/problems/redundant-connection/" },
  { title: "Number of Connected Components in an Undirected Graph", category: "Graph", difficulty: "Medium", link: "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/" },
  { title: "Graph Valid Tree", category: "Graph", difficulty: "Medium", link: "https://leetcode.com/problems/graph-valid-tree/" },
  { title: "Network Delay Time", category: "Graph", difficulty: "Medium", link: "https://leetcode.com/problems/network-delay-time/" },
  { title: "Cheapest Flights Within K Stops", category: "Graph", difficulty: "Medium", link: "https://leetcode.com/problems/cheapest-flights-within-k-stops/" },
  { title: "Word Ladder", category: "Graph", difficulty: "Hard", link: "https://leetcode.com/problems/word-ladder/" },
  { title: "Reconstruct Itinerary", category: "Graph", difficulty: "Hard", link: "https://leetcode.com/problems/reconstruct-itinerary/" },
  { title: "Longest Increasing Path in a Matrix", category: "Graph", difficulty: "Hard", link: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/" },
  { title: "Bus Routes", category: "Graph", difficulty: "Hard", link: "https://leetcode.com/problems/bus-routes/" },

  // --- 12. Dynamic Programming ---
  { title: "Fibonacci Number", category: "Dynamic Programming", difficulty: "Easy", link: "https://leetcode.com/problems/fibonacci-number/" },
  { title: "Climbing Stairs", category: "Dynamic Programming", difficulty: "Easy", link: "https://leetcode.com/problems/climbing-stairs/" },
  { title: "Min Cost Climbing Stairs", category: "Dynamic Programming", difficulty: "Easy", link: "https://leetcode.com/problems/min-cost-climbing-stairs/" },
  { title: "Pascal's Triangle", category: "Dynamic Programming", difficulty: "Easy", link: "https://leetcode.com/problems/pascals-triangle/" },
  { title: "N-th Tribonacci Number", category: "Dynamic Programming", difficulty: "Easy", link: "https://leetcode.com/problems/n-th-tribonacci-number/" },
  { title: "House Robber", category: "Dynamic Programming", difficulty: "Medium", link: "https://leetcode.com/problems/house-robber/" },
  { title: "House Robber II", category: "Dynamic Programming", difficulty: "Medium", link: "https://leetcode.com/problems/house-robber-ii/" },
  { title: "Longest Palindromic Substring", category: "Dynamic Programming", difficulty: "Medium", link: "https://leetcode.com/problems/longest-palindromic-substring/" },
  { title: "Palindromic Substrings", category: "Dynamic Programming", difficulty: "Medium", link: "https://leetcode.com/problems/palindromic-substrings/" },
  { title: "Decode Ways", category: "Dynamic Programming", difficulty: "Medium", link: "https://leetcode.com/problems/decode-ways/" },
  { title: "Coin Change", category: "Dynamic Programming", difficulty: "Medium", link: "https://leetcode.com/problems/coin-change/" },
  { title: "Coin Change II", category: "Dynamic Programming", difficulty: "Medium", link: "https://leetcode.com/problems/coin-change-ii/" },
  { title: "Maximum Product Subarray", category: "Dynamic Programming", difficulty: "Medium", link: "https://leetcode.com/problems/maximum-product-subarray/" },
  { title: "Word Break", category: "Dynamic Programming", difficulty: "Medium", link: "https://leetcode.com/problems/word-break/" },
  { title: "Longest Increasing Subsequence", category: "Dynamic Programming", difficulty: "Medium", link: "https://leetcode.com/problems/longest-increasing-subsequence/" },
  { title: "Partition Equal Subset Sum", category: "Dynamic Programming", difficulty: "Medium", link: "https://leetcode.com/problems/partition-equal-subset-sum/" },
  { title: "Target Sum", category: "Dynamic Programming", difficulty: "Medium", link: "https://leetcode.com/problems/target-sum/" },
  { title: "Unique Paths", category: "Dynamic Programming", difficulty: "Medium", link: "https://leetcode.com/problems/unique-paths/" },
  { title: "Longest Common Subsequence", category: "Dynamic Programming", difficulty: "Medium", link: "https://leetcode.com/problems/longest-common-subsequence/" },
  { title: "Edit Distance", category: "Dynamic Programming", difficulty: "Hard", link: "https://leetcode.com/problems/edit-distance/" },
  { title: "Burst Balloons", category: "Dynamic Programming", difficulty: "Hard", link: "https://leetcode.com/problems/burst-balloons/" },
  { title: "Regular Expression Matching", category: "Dynamic Programming", difficulty: "Hard", link: "https://leetcode.com/problems/regular-expression-matching/" },
  { title: "Distinct Subsequences", category: "Dynamic Programming", difficulty: "Hard", link: "https://leetcode.com/problems/distinct-subsequences/" },
  { title: "Longest Valid Parentheses", category: "Dynamic Programming", difficulty: "Hard", link: "https://leetcode.com/problems/longest-valid-parentheses/" },

  // --- 13. Greedy & Intervals ---
  { title: "Meeting Rooms", category: "Intervals", difficulty: "Easy", link: "https://leetcode.com/problems/meeting-rooms/" },
  { title: "Assign Cookies", category: "Greedy", difficulty: "Easy", link: "https://leetcode.com/problems/assign-cookies/" },
  { title: "Lemonade Change", category: "Greedy", difficulty: "Easy", link: "https://leetcode.com/problems/lemonade-change/" },
  { title: "Maximum Units on a Truck", category: "Greedy", difficulty: "Easy", link: "https://leetcode.com/problems/maximum-units-on-a-truck/" },
  { title: "Jump Game", category: "Greedy", difficulty: "Medium", link: "https://leetcode.com/problems/jump-game/" },
  { title: "Jump Game II", category: "Greedy", difficulty: "Medium", link: "https://leetcode.com/problems/jump-game-ii/" },
  { title: "Gas Station", category: "Greedy", difficulty: "Medium", link: "https://leetcode.com/problems/gas-station/" },
  { title: "Hand of Straights", category: "Greedy", difficulty: "Medium", link: "https://leetcode.com/problems/hand-of-straights/" },
  { title: "Merge Triplets to Form Target Triplet", category: "Greedy", difficulty: "Medium", link: "https://leetcode.com/problems/merge-triplets-to-form-target-triplet/" },
  { title: "Valid Parenthesis String", category: "Greedy", difficulty: "Medium", link: "https://leetcode.com/problems/valid-parenthesis-string/" },
  { title: "Insert Interval", category: "Intervals", difficulty: "Medium", link: "https://leetcode.com/problems/insert-interval/" },
  { title: "Merge Intervals", category: "Intervals", difficulty: "Medium", link: "https://leetcode.com/problems/merge-intervals/" },
  { title: "Non-overlapping Intervals", category: "Intervals", difficulty: "Medium", link: "https://leetcode.com/problems/non-overlapping-intervals/" },
  { title: "Meeting Rooms II", category: "Intervals", difficulty: "Medium", link: "https://leetcode.com/problems/meeting-rooms-ii/" },
  { title: "Minimum Number of Arrows to Burst Balloons", category: "Intervals", difficulty: "Medium", link: "https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/" },
  { title: "Partition Labels", category: "Greedy", difficulty: "Medium", link: "https://leetcode.com/problems/partition-labels/" },
  { title: "Minimum Interval to Include Each Query", category: "Intervals", difficulty: "Hard", link: "https://leetcode.com/problems/minimum-interval-to-include-each-query/" },
  { title: "Candy", category: "Greedy", difficulty: "Hard", link: "https://leetcode.com/problems/candy/" },
  { title: "Course Schedule III", category: "Greedy", difficulty: "Hard", link: "https://leetcode.com/problems/course-schedule-iii/" },

  // --- 14. Math & Bit Manipulation ---
  { title: "Happy Number", category: "Math & Geometry", difficulty: "Easy", link: "https://leetcode.com/problems/happy-number/" },
  { title: "Plus One", category: "Math & Geometry", difficulty: "Easy", link: "https://leetcode.com/problems/plus-one/" },
  { title: "Add Digits", category: "Math & Geometry", difficulty: "Easy", link: "https://leetcode.com/problems/add-digits/" },
  { title: "Single Number", category: "Bit Manipulation", difficulty: "Easy", link: "https://leetcode.com/problems/single-number/" },
  { title: "Number of 1 Bits", category: "Bit Manipulation", difficulty: "Easy", link: "https://leetcode.com/problems/number-of-1-bits/" },
  { title: "Counting Bits", category: "Bit Manipulation", difficulty: "Easy", link: "https://leetcode.com/problems/counting-bits/" },
  { title: "Reverse Bits", category: "Bit Manipulation", difficulty: "Easy", link: "https://leetcode.com/problems/reverse-bits/" },
  { title: "Missing Number", category: "Bit Manipulation", difficulty: "Easy", link: "https://leetcode.com/problems/missing-number/" },
  { title: "Power of Two", category: "Bit Manipulation", difficulty: "Easy", link: "https://leetcode.com/problems/power-of-two/" },
  { title: "Rotate Image", category: "Math & Geometry", difficulty: "Medium", link: "https://leetcode.com/problems/rotate-image/" },
  { title: "Spiral Matrix", category: "Math & Geometry", difficulty: "Medium", link: "https://leetcode.com/problems/spiral-matrix/" },
  { title: "Set Matrix Zeroes", category: "Math & Geometry", difficulty: "Medium", link: "https://leetcode.com/problems/set-matrix-zeroes/" },
  { title: "Pow(x, n)", category: "Math & Geometry", difficulty: "Medium", link: "https://leetcode.com/problems/powx-n/" },
  { title: "Detect Squares", category: "Math & Geometry", difficulty: "Medium", link: "https://leetcode.com/problems/detect-squares/" },
  { title: "Reverse Integer", category: "Math & Geometry", difficulty: "Medium", link: "https://leetcode.com/problems/reverse-integer/" },
  { title: "Multiply Strings", category: "Math & Geometry", difficulty: "Medium", link: "https://leetcode.com/problems/multiply-strings/" },
  { title: "Sum of Two Integers", category: "Bit Manipulation", difficulty: "Medium", link: "https://leetcode.com/problems/sum-of-two-integers/" },
  { title: "Single Number II", category: "Bit Manipulation", difficulty: "Medium", link: "https://leetcode.com/problems/single-number-ii/" },
  { title: "Single Number III", category: "Bit Manipulation", difficulty: "Medium", link: "https://leetcode.com/problems/single-number-iii/" },
  { title: "Bitwise AND of Numbers Range", category: "Bit Manipulation", difficulty: "Medium", link: "https://leetcode.com/problems/bitwise-and-of-numbers-range/" },
  { title: "Max Points on a Line", category: "Math & Geometry", difficulty: "Hard", link: "https://leetcode.com/problems/max-points-on-a-line/" },
  { title: "Basic Calculator", category: "Math & Geometry", difficulty: "Hard", link: "https://leetcode.com/problems/basic-calculator/" },
  { title: "Number of Digit One", category: "Math & Geometry", difficulty: "Hard", link: "https://leetcode.com/problems/number-of-digit-one/" },
  { title: "Minimum One Bit Operations to Make Integers Zero", category: "Bit Manipulation", difficulty: "Hard", link: "https://leetcode.com/problems/minimum-one-bit-operations-to-make-integers-zero/" },
];

export default dsaQuestions;